#---------------------------------- dataset -----------------------------------------#
# dataset: unimib
# n_feature: 3
# len_sw: 151
# n_class: 17

# target_domain: 1
# n_domains: 4
# n_target_domains: 1

#------------------------------------ training -------------------------------------------#
# batch_size: 128
n_epoch: 100
seed: 10
interval_validate: 25
out_path: './logs'
save_model: True

#-------------------------------------- model -------------------------------------------#
model: 'cnn'
res: False
resume: False

#---------------------------------- optimizer -------------------------------------------#
lr: 1e-2
wd: 5e-4
lr_decrease_rate: 0.5
lr_decrease_interval: 20
