#-------------------------------------- dataset -----------------------------------------#
dataset: oppo
n_feature: 77
len_sw: 30
n_class: 17

target_domain: S1
n_domains: 4
n_target_domains: 1

#------------------------------------ training ------------------------------------------#
batch_size: 1000
# n_epoch: 100
seed: 10
interval_validate: 25
out_path: './logs'
save_model: True

#-------------------------------------- model -------------------------------------------#
model: 'cnn'
res: False
resume: './ckpt'

