#---------------------------------- optimizer -------------------------------------------#
lr: 1e-2
wd: 0.0
lr_decrease_rate: 0.5
lr_decrease_interval: 20

#---------------------------------- adaptating -------------------------------------------#
return_feature: False
adaption: 'shot'
# filter_K: 25